data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  temp_dir: "data/temp"
  raw_satellite_dir: "data/raw/satellite"
  processed_satellite_dir: "data/processed/satellite"
  launch_stats_file: "launch_stats_actuals.csv"
  launch_forecast_file: "launch_forecast_actuals.csv"
  weather_hourly_file: "ccsfs_hourly_step_wx_data.csv"
  clean_launch_stats_file: "clean_launch_stats.csv"
  clean_launch_forecast_file: "clean_launch_forecast.csv"
  goes_imagery_folder: "visible"
  shear_imagery_folder: "shear"
  warning_imagery_folder: "warning"
  sbcape_cin_imagery_folder: "sbcape"